### PR TITLE
snyk updates

### PR DESCRIPTION
**Pull request by epitaphmike**

### CODE REVIEW

**Comment by epitaphmike** [comment]
@peterpme do I not have write access to merge pull requests? I made an update this morning to take care of some vulnerabilities and wanted to update the active repo. Thanks

**Comment by peterpme** [comment]
my bad, try again! I didn't realize collaborators are "read only"

**Comment by peterpme** [comment]
you are now an admin

**Comment by epitaphmike** [comment]
Thanks. Also. Nice work on apollo-tote!

**Pull request merged**
